### PR TITLE
Prototype

### PR DESCRIPTION
**Pull request by zceaton**
Pulling the prototype into the develop branch for the submission of this part of the project.

### CODE REVIEW

**Comment by abarganier** [comment]
Looks good, going to merge into develop now.

**Comment by hartloff** [comment]
What issue does this resolve?

**Comment by abarganier** [comment]
It doesn't resolve any issue because it's a release. The issues resolved in this release have their own GitHub issues.

**Comment by zceaton** [comment]
Will do, my bad.

**Pull request merged**
